# Site settings
title: 夜闲戏 Blog
SEOTitle: 夜闲戏的博客 | 夜闲戏 Blog
header-img: img/home-bg.jpg
email: zheng2499815410@gmail.com
description: "这里是 @夜闲戏 的个人博客，与你一起发现更大的世界 | 要做一个有 swag 的程序员"
keyword: "夜闲戏, 夜闲戏的博客, 夜闲戏 Blog, 博客, 个人网站, 互联网, Web, JavaScript, React, React Native, 前端, 设计"
url: "https://huangxuan.me" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# SNS settings
RSS: false
weibo_username: zhengzheng0201
zhihu_username: zhengzheng0201
github_username: zhengzheng0201
twitter_username: "https://x.com/zhengzheng0201" # 直接放入完整的推特链接
#facebook_username:  zhengzheng0201
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true
#timezone: CN

# Gems
plugins: [jekyll-paginate]

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: zhengzheng0201

# Analytics settings
ga_track_id: "UA-49627206-1" 
ga_domain: huangxuan.me

# Sidebar settings
sidebar: true
sidebar-about-description: "要做一个有 swag 的程序员 <br> React Team @ Meta"
sidebar-avatar: https://github.com/zhengzheng0201.png

# Featured Tags
featured-tags: true
featured-condition-size: 1

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends:
  [
    { title: "乱序（Midare）", href: "http://mida.re/" },
    { title: "Ebn Zhang", href: "https://ebnbin.dev/" },
    { title: "Kun Qian", href: "http://kunq.me" },
    { title: "Sherry Woo", href: "https://sherrywoo.me/" },
    { title: "SmdCn", href: "http://blog.smdcn.net" },
    { title: "JiyinYiyong", href: "http://tiye.me/" },
    { title: "DHong Say", href: "http://dhong.co" },
    { title: "尹峰以为", href: "http://ingf.github.io/" },
  ]
